name: Github DMD
on: [push]
jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    container: docker://dvcorg-py3:latest
    steps:

      - uses: actions/checkout@v2
      - name: dmd test
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python dmd.py
