name: Github DMD
on: [push]
jobs:
  train-and-report:
    runs-on: ubuntu-latest

    # optionally use a convenient Ubuntu LTS + DVC + CML image
    #container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v3
      - name: dmd test
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python dmd.py
          
          
          cat metrics.txt >> report.md
          cml-publish functions.png --md >> report.md
          # cml-publish eigs.png --md >> report.md
          # cml-publish modes.png --md >> report.md
          # cml-publish dynamics.png --md >> report.md
          # cml-publish reconstruction.png --md >> report.md

          # cml-send-comment report.md
