name: Github DMD
on: [push]
jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest

    # optionally use a convenient Ubuntu LTS + DVC + CML image
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:

      - uses: actions/checkout@v2
      - name: dmd test
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python dmd.py
